# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Develop

on:
  push:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: ./install.sh
      - run: ./build.sh
      - run: npm ci

  publish-npm:
    if: ${{github.event.pull_request.merged == true}} && contains('refs/heads/develop refs/heads/release/', github.ref)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: ./version_updater.sh
      - run: npm ci
      - run: npm publish
      - run: git push
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
